### ISSUE TITLE
defineComputed 传入的回调会累加执行（1、3、7、15次执行）

### ISSUE THREAD

**Issue by 1221key** [doodlewind/nano-computed#1]
elder.now = 2018
3   VM186:73 Now his age is 92

elder.now = 2019
7 VM186:73 Now his age is 93

elder.now = 2020
15 VM186:73 Now his age is 94

elder.now = 2020
31 VM186:73 Now his age is 94

**Comment by doodlewind** [comment]
谢谢，回调不应该多次执行
